# [[main]]
#    identifier = "<id>" where <id> is what's used in this menu file for organization of parents
#    name = "<name_id>" where <name_id> is what shows up in dropdown menu
#    url = "/<url_id>" where <url_id> must (case insensitive) match name in index.md title frontmatter, which is the "real" URL and this is the alias
#    weight = <weight_id> where <weight_id> indicates order in dropdown

[[main]]
    # Top-level menu entry
    identifier = "about"
    name = "About"
    url = "/about/"
    #parent = "work"
    weight = 10

[[main]]
    # Top-level menu entry
    identifier = "work"
    name = "Work"
    url = "/projects/"
    weight = 20

    [[main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        parent = "work"
        weight = 21
    [[main]]
        identifier = "career"
        name = "Career Thoughts"
        url = "/tags/career/"
        parent = "work"
        weight = 22

[[main]]
    # Top-level menu entry
    identifier = "writing"
    name = "Writing"
    url = "/posts/"
    weight = 30

    [[main]]
        identifier = "posts"
        name = "All Posts"
        url = "/posts/"
        parent = "writing"
        weight = 31
    [[main]]
        identifier = "mental health"
        name = "Mental Health"
        url = "/mental health/"
        parent = "writing"
        weight = 32
    [[main]]
        identifier = "personal finance"
        name = "Personal Finance"
        url = "/personal finance/"
        parent = "writing"
        weight = 33
    [[main]]
        identifier = "tech and tools"
        name = "Tech and Tools"
        url = "/tech and tools/"
        parent = "writing"
        weight = 34

[[main]]
    # Top-level menu entry
    identifier = "explore"
    name = "Explore"
    url = "/categories/"
    weight = 40

    [[main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        parent = "explore"
        weight = 41
    [[main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        parent = "explore"
        weight = 42
    [[main]]
        identifier = "series"
        name = "Series"
        url = "/series/"
        parent = "explore"
        weight = 43
    [[main]]
        identifier = "project-type"
        name = "Project Types"
        url = "/project-types/"
        parent = "explore"
        weight = 44