### SEO, Analytics & 3rd-party
netlify_forms = false # add data-netlify attribute to contact and newsletter forms, false to disable Netlify forms
# gtm_id = '' # GTM tracking (leave blank to use GA)
disallow_search_engines = false # Disallow search engine crawling in robots.txt

### Content
favicon = true # Enable favicon, add your favicon files to /static/ directory
avatar = '_profile_pic.png' # Custom avatar image in /assets/
grayscale_avatar = false # Add a grayscale filter to the avatar image
author = 'Farhan Sareshwala' # Default author for <head> meta
description = "Personal blog and portfolio site of Farhan Sareshwala." # Add a global meta description to <head>
#footer_text = "\nBuilt with [Hugo Liftoff](https://github.com/wjh18/hugo-liftoff) theme." # Customize footer text
fallback_text = "No content available yet. Coming soon." # Fallback text for empty content
label_drafts = true # Add a label indicator next to the title of any built drafts (dev only)

# Customize newsletter text
global_newsletter = false # Enable newsletter site-wide

# CSS / JavaScript
enable_postcss = false # Enable if you're using npm and want to utilize PostCSS processing
#custom_css = 'custom.css' # Add the specified file to assets before setting this param to avoid errors
#custom_js = 'custom.js' # Add the specified file to assets before setting this param to avoid errors

### Web schemas
# Open Graph
images = ['images/default.png'] # Fallback for Open Graph and Twitter Cards images if none are present in front matter. Enter path to the image.
ogLocale = "en_US" # Open graph locale

# Twitter Cards
#twitterSite = "johndoestwitter" # Enter your twitter handle without the @
#twitterCreator = "johndoestwitter" # Enter your twitter handle without the @

# JSON-LD structured data schemas
schemaName = "Farhan Sareshwala" # Enter your name
schemaLocale = "en-US" # Structured data locale
schemaImage = "images/profile_pic.png" # Image for Person structured data schema. Enter path to the image.
schemaImageWidth = 453 # Width of the above image
schemaImageHeight = 455 # Height of the above image

### Social
# Show social links in footer, home hero section, or about page
footer_socials = true
home_hero_socials = true
about_page_socials = true

# Enable or disable individual social icons
[social.links]
  email = "hello@fsaresh.com"
  github = "fsaresh"
  linkedin = "fsaresh"
  #twitter = "username"
  #stack_overflow = "userid/username" # include user id

# Enable or disable individual social share icons in posts
[social.share]
  email = true
  linkedin = true
  facebook = false
  twitter = false
  reddit = false
